'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.5420
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("ImageFormatConverter.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        Friend ReadOnly Property about_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("about_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_161() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_161", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property add_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("add_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property exit_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("exit_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property go_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("go_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property go_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("go_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property go_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("go_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property head() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("head", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property help_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("help_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property home_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("home_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property in_folder_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("in_folder_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property in_folder_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("in_folder_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property in_folder_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("in_folder_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mail_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property mail_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mail_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new_32() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_32", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new_321() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_321", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property new_48() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new_48", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        Friend ReadOnly Property out_folder_16() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("out_folder_16", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
